# Generated by Django 4.0.3 on 2022-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя знаменитости')),
                ('description', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Знаменитость на киноиндустрий',
                'verbose_name_plural': 'Знаменитости на киноиндустрий',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя знаменитости')),
                ('description', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Знаменитость по литературе',
                'verbose_name_plural': 'Знаменитости по литературе',
            },
        ),
        migrations.CreateModel(
            name='Maths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя знаменитости')),
                ('description', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Знаменитость по математике',
                'verbose_name_plural': 'Знаменитости по математике',
            },
        ),
        migrations.AlterModelOptions(
            name='celebrities',
            options={'verbose_name': 'Знаменитость', 'verbose_name_plural': 'Знаменитости'},
        ),
    ]
