# Generated by Django 4.0.3 on 2022-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_film_literature_maths_alter_celebrities_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrities',
            options={'verbose_name': 'Знаменитости', 'verbose_name_plural': 'Все'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Знаменитости на киноиндустрий', 'verbose_name_plural': 'Киноиндустрия'},
        ),
        migrations.AlterModelOptions(
            name='literature',
            options={'verbose_name': 'Знаменитости по литературе', 'verbose_name_plural': 'Литература'},
        ),
        migrations.AlterModelOptions(
            name='maths',
            options={'verbose_name': 'Знаменитости по математике', 'verbose_name_plural': 'Математика'},
        ),
        migrations.AddField(
            model_name='celebrities',
            name='link',
            field=models.TextField(default='Some String', verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='film',
            name='link',
            field=models.TextField(default='Some String', verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='literature',
            name='link',
            field=models.TextField(default='Some String', verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='maths',
            name='link',
            field=models.TextField(default='Some String', verbose_name='Ссылка на фото'),
        ),
    ]
