# Generated by Django 4.0.3 on 2022-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_celebrities_options_alter_film_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrities',
            name='type',
            field=models.CharField(default='Celebrities', max_length=50, verbose_name='Тип знаменитости'),
        ),
        migrations.AddField(
            model_name='film',
            name='type',
            field=models.CharField(default='Celebrities', max_length=50, verbose_name='Тип знаменитости'),
        ),
        migrations.AddField(
            model_name='literature',
            name='type',
            field=models.CharField(default='Celebrities', max_length=50, verbose_name='Тип знаменитости'),
        ),
        migrations.AddField(
            model_name='maths',
            name='type',
            field=models.CharField(default='Celebrities', max_length=50, verbose_name='Тип знаменитости'),
        ),
    ]
